CREATE TYPE "virtual_tryon_mode" AS ENUM ('front_only', 'three_view');
CREATE TYPE "virtual_tryon_job_status" AS ENUM ('draft', 'queued', 'generating', 'qa_queued', 'ready', 'locked', 'failed_released', 'failed_refunded');
CREATE TYPE "appearance_pack_status" AS ENUM ('draft', 'generating', 'qa_queued', 'ready', 'locked', 'failed');
CREATE TYPE "appearance_view" AS ENUM ('front', 'side', 'back');

CREATE TABLE "virtual_tryon_jobs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "user_id" text NOT NULL, "mode" "virtual_tryon_mode" NOT NULL, "status" "virtual_tryon_job_status" NOT NULL DEFAULT 'draft', "sku_name" text, "create_idempotency_key" text NOT NULL, "source_snapshot" jsonb NOT NULL, "model_snapshot" jsonb NOT NULL, "rights_snapshot" jsonb NOT NULL, "credit_cost" integer NOT NULL, "reserved_ledger_id" uuid, "captured_ledger_id" uuid, "locked_by" text, "locked_until" timestamptz, "attempt_count" integer NOT NULL DEFAULT 0, "last_error" text, "next_retry_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), "deleted_at" timestamptz);
CREATE UNIQUE INDEX "virtual_tryon_jobs_owner_idempotency_unique" ON "virtual_tryon_jobs" ("user_id", "create_idempotency_key");
CREATE TABLE "appearance_packs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "virtual_tryon_job_id" uuid NOT NULL, "version" integer NOT NULL, "required_views" jsonb NOT NULL, "status" "appearance_pack_status" NOT NULL DEFAULT 'draft', "qa_summary" jsonb, "locked_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX "appearance_packs_job_version_unique" ON "appearance_packs" ("virtual_tryon_job_id", "version");
CREATE TABLE "appearance_pack_assets" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "appearance_pack_id" uuid NOT NULL, "view" "appearance_view" NOT NULL, "provider_task_id" text, "provider_status" text NOT NULL DEFAULT 'pending', "attempt_count" integer NOT NULL DEFAULT 0, "r2_key" text, "origin" text NOT NULL DEFAULT 'generated_apimart_gpt_image_2', "provenance" jsonb NOT NULL, "last_error_code" text, "next_retry_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX "appearance_pack_assets_pack_view_unique" ON "appearance_pack_assets" ("appearance_pack_id", "view");
CREATE TABLE "garment_fidelity_results" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "appearance_pack_id" uuid NOT NULL, "scope" text NOT NULL, "view" "appearance_view", "verdict" text NOT NULL, "result_json" jsonb NOT NULL, "provider_call_log_id" uuid, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX "garment_fidelity_results_pack_scope_view_unique" ON "garment_fidelity_results" ("appearance_pack_id", "scope", "view");
CREATE TABLE "virtual_tryon_state_events" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "virtual_tryon_job_id" uuid NOT NULL, "from_status" text, "to_status" text NOT NULL, "reason" text NOT NULL, "actor_type" text NOT NULL DEFAULT 'system', "event_snapshot" jsonb, "created_at" timestamptz NOT NULL DEFAULT now());
