import { createHash } from "node:crypto";
import type { ProviderCallLogStore } from "@/lib/providers/log-call";
import { createVisionVirtualTryOnQa, type VisionVirtualTryOnQaResult } from "@/lib/providers/vision/client";
import type { AppearanceView, VirtualTryOnMode } from "./config";
import { isStrictCrossViewQaPass, isStrictViewQaPass, parseStrictCrossViewQa, parseStrictViewQa } from "./qa-schema";
import type { VirtualTryOnQaStore } from "./qa-store";

const hash = (value: string) => createHash("sha256").update(value).digest("hex");
export async function runVirtualTryOnQa(input: { jobId: string; userId: string; packId: string; mode: VirtualTryOnMode; sourceKeys: { front: string; back?: string; detail?: string }; generatedKeys: Partial<Record<AppearanceView, string>> }, deps: { signer: (key: string) => Promise<string>; visionProvider?: (input: Parameters<typeof createVisionVirtualTryOnQa>[0]) => Promise<VisionVirtualTryOnQaResult>; qaStore: VirtualTryOnQaStore; providerLogStore: ProviderCallLogStore }) {
  const views: AppearanceView[] = input.mode === "front_only" ? ["front"] : ["front", "side", "back"]; const verdicts: Record<string, string> = {}; let allPassed = true;
  for (const view of views) {
    try { const generated = input.generatedKeys[view]; if (!generated) throw new Error("generated_view_missing"); const keys = [input.sourceKeys.front, ...(input.sourceKeys.back ? [input.sourceKeys.back] : []), ...(input.sourceKeys.detail ? [input.sourceKeys.detail] : []), generated]; const urls = await Promise.all(keys.map(deps.signer)); const result = await (deps.visionProvider ?? createVisionVirtualTryOnQa)({ kind: "view", imageUrls: urls, targetView: view, requirements: ["preserve garment" ] }); const qa = parseStrictViewQa(result.qaJson); verdicts[view] = qa.verdict; allPassed &&= isStrictViewQaPass(qa, view); await deps.qaStore.upsertViewResult(input.packId, view, qa); await deps.providerLogStore.createCallLog({ provider: result.provider, model: result.model, purpose: "virtual_tryon_qa", userId: input.userId, virtualTryonJobId: input.jobId, requestSnapshot: { scope: "view", view, imageCount: urls.length, promptHash: hash(view) }, responseSummary: { verdict: qa.verdict, status: "completed" }, status: "succeeded" }); }
    catch { verdicts[view] = "unknown"; allPassed = false; await deps.qaStore.upsertViewResult(input.packId, view, { verdict: "unknown" }); await deps.providerLogStore.createCallLog({ provider: "vision", model: "strict", purpose: "virtual_tryon_qa", userId: input.userId, virtualTryonJobId: input.jobId, requestSnapshot: { scope: "view", view, imageCount: 0, promptHash: hash(view) }, responseSummary: { verdict: "unknown", status: "failed" }, status: "failed", errorCode: "virtual_tryon_qa_failed", errorMessage: "Virtual try-on QA failed." }); }
  }
  let crossVerdict: string | null = null;
  if (input.mode === "three_view") { try { const urls = await Promise.all(views.map((view) => { const key = input.generatedKeys[view]; if (!key) throw new Error("generated_view_missing"); return deps.signer(key); })); const result = await (deps.visionProvider ?? createVisionVirtualTryOnQa)({ kind: "cross", imageUrls: urls, requiredViews: views, requirements: ["cross view consistency"] }); const qa = parseStrictCrossViewQa(result.qaJson); crossVerdict = qa.verdict; allPassed &&= isStrictCrossViewQaPass(qa, views); await deps.qaStore.upsertCrossResult(input.packId, qa); await deps.providerLogStore.createCallLog({ provider: result.provider, model: result.model, purpose: "virtual_tryon_qa", userId: input.userId, virtualTryonJobId: input.jobId, requestSnapshot: { scope: "cross", imageCount: urls.length, promptHash: hash("front,side,back") }, responseSummary: { verdict: qa.verdict, status: "completed" }, status: "succeeded" }); } catch { crossVerdict = "unknown"; allPassed = false; await deps.qaStore.upsertCrossResult(input.packId, { verdict: "unknown" }); await deps.providerLogStore.createCallLog({ provider: "vision", model: "strict", purpose: "virtual_tryon_qa", userId: input.userId, virtualTryonJobId: input.jobId, requestSnapshot: { scope: "cross", imageCount: 0, promptHash: hash("front,side,back") }, responseSummary: { verdict: "unknown", status: "failed" }, status: "failed", errorCode: "virtual_tryon_qa_failed", errorMessage: "Virtual try-on QA failed." }); } }
  const summary = { allPassed, views: verdicts, crossVerdict }; await deps.qaStore.updateQaSummary(input.packId, summary); return summary;
}
