import type { DemoCase } from "./types";

export const demoCases = [
  {
    slug: "burgundy-midi-dress",
    category: "dress",
    sourceType: "synthetic-demo",
    status: "published",
    title: {
      en: "Adult burgundy midi dress",
      "zh-CN": "成人深酒红中长连衣裙",
    },
    summary: {
      en: "A traceable synthetic adult-womenswear source set with a real minimal-studio workflow result.",
      "zh-CN": "一套可追溯的合成成人女装素材，并已通过真实极简棚拍工作流生成成片。",
    },
    sourceNote: {
      en: "Synthetic product input generated with ImageGen. The video was generated by the product workflow, not by CSS animation.",
      "zh-CN": "商品输入由 ImageGen 合成；视频由产品真实链路生成，不是 CSS 动效。",
    },
    boundaryNote: {
      en: "The approved front-push-in shot preserves the uploaded V neckline, long sleeves, waist seam, A-line hem, and matte crepe texture.",
      "zh-CN": "已通过的正面慢推近镜头保留了素材中的 V 领、长袖、腰线、A 字裙摆与哑光绉面质感。",
    },
    featuredImage: "/demo/cases/burgundy-midi-dress/front.webp",
    sourceAssets: [
      {
        role: "front",
        src: "/demo/cases/burgundy-midi-dress/front.webp",
        alt: {
          en: "Synthetic front product image of an adult burgundy midi dress",
          "zh-CN": "成人深酒红中长连衣裙合成正面商品图",
        },
      },
      {
        role: "back",
        src: "/demo/cases/burgundy-midi-dress/back.webp",
        alt: {
          en: "Synthetic back product image of an adult burgundy midi dress",
          "zh-CN": "成人深酒红中长连衣裙合成背面商品图",
        },
      },
      {
        role: "detail",
        src: "/demo/cases/burgundy-midi-dress/detail.webp",
        alt: {
          en: "Synthetic neckline and waist detail of an adult burgundy midi dress",
          "zh-CN": "成人深酒红中长连衣裙合成领口与腰线细节图",
        },
      },
    ],
    featuredOutput: {
      videoSrc: "/demo/cases/burgundy-midi-dress/minimal-studio.mp4",
      posterSrc: "/demo/cases/burgundy-midi-dress/minimal-studio-poster.webp",
      presetId: "minimal_studio",
    },
  },
  {
    slug: "structured-blazer",
    category: "blazer",
    sourceType: "synthetic-demo",
    status: "source-ready",
    title: {
      en: "Cobalt structured blazer",
      "zh-CN": "钴蓝结构化西装外套",
    },
    summary: {
      en: "A synthetic front, back, and lapel-detail source set prepared for controlled Preset comparison.",
      "zh-CN": "为同源 Preset 对比准备的合成正面、背面与驳领细节素材。",
    },
    sourceNote: {
      en: "Synthetic product input generated with ImageGen. It is not a customer case.",
      "zh-CN": "使用 ImageGen 生成的合成商品输入，不是客户案例。",
    },
    boundaryNote: {
      en: "No person or scene image is provided. Social lifestyle must remain a restrained product treatment.",
      "zh-CN": "没有真人或场景图；社媒氛围 Preset 只能保持克制的商品展示。",
    },
    featuredImage: "/demo/cases/structured-blazer/front.webp",
    sourceAssets: [
      {
        role: "front",
        src: "/demo/cases/structured-blazer/front.webp",
        alt: {
          en: "Synthetic front product image of a cobalt structured blazer",
          "zh-CN": "钴蓝结构化西装外套合成正面商品图",
        },
      },
      {
        role: "back",
        src: "/demo/cases/structured-blazer/back.webp",
        alt: {
          en: "Synthetic back product image of a cobalt structured blazer",
          "zh-CN": "钴蓝结构化西装外套合成背面商品图",
        },
      },
      {
        role: "detail",
        src: "/demo/cases/structured-blazer/detail.webp",
        alt: {
          en: "Synthetic lapel and button detail of a cobalt structured blazer",
          "zh-CN": "钴蓝结构化西装外套合成驳领与纽扣细节图",
        },
      },
    ],
    featuredOutput: null,
  },
  {
    slug: "knit-cardigan",
    category: "cardigan",
    sourceType: "synthetic-demo",
    status: "source-ready",
    title: {
      en: "Sage rib-knit cardigan",
      "zh-CN": "鼠尾草绿罗纹针织开衫",
    },
    summary: {
      en: "A synthetic front, back, and knit-detail source set for clean marketplace motion.",
      "zh-CN": "用于电商主图动效的合成正面、背面与针织细节素材。",
    },
    sourceNote: {
      en: "Synthetic product input generated with ImageGen. It is not a customer case.",
      "zh-CN": "使用 ImageGen 生成的合成商品输入，不是客户案例。",
    },
    boundaryNote: {
      en: "The visible knit, neckline, buttons, and silhouette are the complete product evidence.",
      "zh-CN": "可见针织纹理、领口、纽扣与版型构成全部商品依据。",
    },
    featuredImage: "/demo/cases/knit-cardigan/front.webp",
    sourceAssets: [
      {
        role: "front",
        src: "/demo/cases/knit-cardigan/front.webp",
        alt: {
          en: "Synthetic front product image of a sage rib-knit cardigan",
          "zh-CN": "鼠尾草绿罗纹针织开衫合成正面商品图",
        },
      },
      {
        role: "back",
        src: "/demo/cases/knit-cardigan/back.webp",
        alt: {
          en: "Synthetic back product image of a sage rib-knit cardigan",
          "zh-CN": "鼠尾草绿罗纹针织开衫合成背面商品图",
        },
      },
      {
        role: "detail",
        src: "/demo/cases/knit-cardigan/detail.webp",
        alt: {
          en: "Synthetic neckline, button, and cuff detail of a sage rib-knit cardigan",
          "zh-CN": "鼠尾草绿罗纹针织开衫合成领口、纽扣与袖口细节图",
        },
      },
    ],
    featuredOutput: null,
  },
] as const satisfies readonly DemoCase[];

export function getDemoCase(slug: string) {
  return demoCases.find((item) => item.slug === slug) ?? null;
}
