// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

import Home from "./page";

const mocks = vi.hoisted(() => ({
  getServerSession: vi.fn(),
  getRequestLocale: vi.fn(),
  recordFunnelEventSafely: vi.fn(),
}));

vi.mock("@/lib/auth/server", () => ({
  getServerSession: mocks.getServerSession,
}));

vi.mock("@/server/analytics/funnel-events", () => ({
  recordFunnelEventSafely: mocks.recordFunnelEventSafely,
}));

vi.mock("@/lib/i18n/server", () => ({
  getRequestLocale: mocks.getRequestLocale,
}));

vi.mock("next/navigation", () => ({
  usePathname: () => "/",
  useSearchParams: () => new URLSearchParams(),
}));

vi.mock("@/components/dashboard/sign-out-button", () => ({
  SignOutButton: () => <button type="button">Sign out</button>,
}));

describe("Home", () => {
  afterEach(() => {
    cleanup();
    vi.clearAllMocks();
  });

  it("uses English by default and anchors the homepage in real evidence", async () => {
    mocks.getServerSession.mockResolvedValue(null);
    mocks.getRequestLocale.mockResolvedValue("en");

    render(await Home());

    expect(
      screen.getByRole("heading", {
        level: 1,
        name: "Three clothing images. One product video.",
      }),
    ).toBeInTheDocument();
    expect(screen.getByText(/front, side, and back appearance references/i)).toBeInTheDocument();
    expect(screen.getByText(/No back image means no back view/i)).toBeInTheDocument();
    expect(
      screen.getByText(/You still verify that the detail image belongs to that garment/i),
    ).toBeInTheDocument();
    const workflowTitle = screen.getByRole("heading", {
      level: 2,
      name: "A controlled workflow from upload to delivery",
    });
    const workflowSection = workflowTitle.closest("section");
    expect(workflowSection).not.toBeNull();
    expect(within(workflowSection as HTMLElement).getAllByRole("listitem"))
      .toHaveLength(4);
    expect(
      within(workflowSection as HTMLElement).getByRole("heading", {
        level: 3,
        name: "Map image evidence",
      }),
    ).toBeInTheDocument();
    expect(
      within(workflowSection as HTMLElement).getByRole("heading", {
        level: 3,
        name: "Match eligible shots",
      }),
    ).toBeInTheDocument();
    const presetTitle = screen.getByRole("heading", {
      level: 2,
      name: "Tell the system where the video will be used",
    });
    const presetSection = presetTitle.closest("section");
    expect(presetSection).not.toBeNull();
    expect(within(presetSection as HTMLElement).getByRole("list"))
      .toHaveClass("md:grid-cols-2", "lg:grid-cols-3");
    expect(screen.getByTestId("landing-hero-video")).toHaveAttribute(
      "src",
      "/demo/cases/burgundy-midi-dress/virtual-try-on-homepage-8s.mp4",
    );
    expect(screen.getByTestId("landing-hero-video")).toHaveClass(
      "landing-hero-video-portrait",
    );
    expect(screen.getByAltText("Front appearance reference of an adult woman wearing a burgundy midi dress")).toHaveAttribute(
      "src",
      expect.stringContaining("/demo/cases/burgundy-midi-dress/appearance-front.webp"),
    );
    expect(screen.getByAltText("Side appearance reference of an adult woman wearing a burgundy midi dress")).toBeInTheDocument();
    expect(screen.getByAltText("Back appearance reference of an adult woman wearing a burgundy midi dress")).toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: "View the generated three-image source set" }),
    ).toHaveAttribute("href", "#source-proof");
    expect(
      screen.getByText(/appearance references were generated by the real virtual-try-on workflow/),
    ).toBeInTheDocument();
    expect(screen.getByText(/24-second version is not used on the public site/)).toBeInTheDocument();
    const evidenceVideo = screen.getByLabelText("Generated adult burgundy midi dress product video");
    expect(evidenceVideo)
      .toHaveAttribute("src", "/demo/cases/burgundy-midi-dress/virtual-try-on-homepage-8s.mp4");
    expect(evidenceVideo)
      .toHaveAttribute("poster", "/demo/cases/burgundy-midi-dress/virtual-try-on-homepage-8s-poster.webp");
    expect(evidenceVideo).toHaveClass("object-contain");
    expect(evidenceVideo.parentElement).toHaveClass("aspect-[9/16]");
    expect(
      screen.getByRole("heading", {
        level: 2,
        name: "Create an 8, 16, 24, or 32-second video for one SKU",
      }),
    ).toBeInTheDocument();
    expect(screen.getByText("32 sec")).toBeInTheDocument();
  }, 15_000);

  it("keeps the Chinese homepage at /zh without mixing languages", async () => {
    mocks.getServerSession.mockResolvedValue(null);
    mocks.getRequestLocale.mockResolvedValue("zh-CN");

    render(await Home());

    expect(screen.getByRole("heading", { level: 1, name: "三张服装图，生成一条商品宣传视频" }))
      .toBeInTheDocument();
    expect(
      screen.getByText(/真人定妆三视图由真实虚拟试穿链路生成/),
    ).toBeInTheDocument();
    expect(screen.getByText(/24 秒完整版不用于公开展示/)).toBeInTheDocument();
    expect(screen.getAllByRole("link", { name: "免费生成 1 条试用视频" })[0])
      .toHaveAttribute("href", "/zh/workspace?mode=trial&preset=minimal_studio");
    expect(
      screen.getByRole("heading", {
        level: 2,
        name: "从上传到交付，每一步都有明确边界",
      }),
    ).toBeInTheDocument();
    expect(screen.getByRole("heading", { level: 3, name: "读取素材依据" }))
      .toBeInTheDocument();
    expect(screen.getByRole("heading", { level: 3, name: "匹配可用镜头" }))
      .toBeInTheDocument();
    expect(screen.getByRole("link", { name: "查看合成三图样例" }))
      .toHaveAttribute("href", "#source-proof");
    expect(screen.getByLabelText("由三张成人深酒红中长裙素材生成的商品视频"))
      .toHaveAttribute("src", "/demo/cases/burgundy-midi-dress/virtual-try-on-homepage-8s.mp4");
    expect(
      screen.getByRole("heading", {
        level: 2,
        name: "查看已经生成的多 SKU 素材",
      }),
    ).toBeInTheDocument();
    expect(screen.getByText("合成演示素材，不是客户案例。"))
      .toBeInTheDocument();
    expect(screen.getByRole("link", { name: "查看全部素材案例" }))
      .toHaveAttribute("href", "/zh/examples");
    expect(
      screen.getByRole("heading", {
        level: 2,
        name: "为一个 SKU 生成 8、16、24 或 32 秒成片",
      }),
    ).toBeInTheDocument();
    expect(screen.getByText("32 秒")).toBeInTheDocument();
  });

  it("shows generated synthetic SKU material and links to the source library", async () => {
    mocks.getServerSession.mockResolvedValue(null);
    mocks.getRequestLocale.mockResolvedValue("en");

    render(await Home());

    expect(
      screen.getByRole("heading", {
        level: 2,
        name: "Inspect the generated multi-SKU source sets",
      }),
    ).toBeInTheDocument();
    expect(screen.getByText("Synthetic demo material, not customer cases."))
      .toBeInTheDocument();
    expect(screen.getByAltText("Cobalt structured blazer front source"))
      .toHaveAttribute(
        "src",
        expect.stringContaining("structured-blazer%2Ffront.webp"),
      );
    expect(screen.getByAltText("Sage rib-knit cardigan detail source"))
      .toHaveAttribute(
        "src",
        expect.stringContaining("knit-cardigan%2Fdetail.webp"),
      );
    expect(screen.getByRole("link", { name: "View all source cases" }))
      .toHaveAttribute("href", "/examples");
  });

  it("exposes video generation and virtual try-on as separate homepage workflows", async () => {
    mocks.getServerSession.mockResolvedValue(null);
    mocks.getRequestLocale.mockResolvedValue("en");

    render(await Home());

    const englishSection = screen
      .getByRole("heading", { level: 2, name: "Choose how to start this SKU" })
      .closest("section");
    expect(englishSection).not.toBeNull();
    expect(within(englishSection as HTMLElement).getByRole("link", { name: "Open virtual try-on" }))
      .toHaveAttribute("href", "/virtual-try-on");
    expect(within(englishSection as HTMLElement).getByRole("link", { name: "Open video workspace" }))
      .toHaveAttribute("href", "/workspace");

    cleanup();
    mocks.getRequestLocale.mockResolvedValue("zh-CN");
    render(await Home());

    const chineseSection = screen
      .getByRole("heading", { level: 2, name: "选择这个 SKU 的创作起点" })
      .closest("section");
    expect(chineseSection).not.toBeNull();
    expect(within(chineseSection as HTMLElement).getByRole("link", { name: "开始虚拟试穿" }))
      .toHaveAttribute("href", "/zh/virtual-try-on");
    expect(within(chineseSection as HTMLElement).getByRole("link", { name: "进入视频工作台" }))
      .toHaveAttribute("href", "/zh/workspace");
  });

  it("shows anonymous trial actions to visitors", async () => {
    mocks.getServerSession.mockResolvedValue(null);
    mocks.getRequestLocale.mockResolvedValue("en");

    render(await Home());

    expect(screen.getByRole("link", { name: "Sign in" })).toHaveAttribute(
      "href",
      "/login",
    );
    expect(screen.getByRole("link", { name: "Free trial" })).toBeInTheDocument();
    expect(
      screen.getAllByRole("link", { name: "Create a free trial video" })[0],
    ).toHaveAttribute("href", "/workspace?mode=trial&preset=minimal_studio");
    expect(
      screen.getByText(
        "8 seconds · low resolution · no audio · watermarked · low-risk shots only",
      ),
    ).toBeInTheDocument();
    expect(mocks.recordFunnelEventSafely).toHaveBeenCalledWith(
      expect.objectContaining({
        eventName: "landing_viewed",
        source: "server",
        userId: null,
        path: "/",
        metadata: { sourcePage: "homepage" },
      }),
    );
  });

  it("shows signed-in workspace actions instead of anonymous trial actions", async () => {
    mocks.getServerSession.mockResolvedValue({
      user: { id: "user-1", email: "merchant@example.com" },
    });
    mocks.getRequestLocale.mockResolvedValue("en");

    render(await Home());

    expect(screen.getByText("merchant@example.com")).toBeInTheDocument();
    expect(screen.getAllByRole("link", { name: "Workspace" })[0]).toHaveAttribute(
      "href",
      "/workspace",
    );
    expect(screen.getAllByRole("link", { name: "Open workspace" })[0]).toHaveAttribute(
      "href",
      "/workspace",
    );
    expect(screen.queryByRole("link", { name: "Sign in" })).not.toBeInTheDocument();
    expect(
      screen.queryByRole("link", { name: "Free trial" }),
    ).not.toBeInTheDocument();
    expect(
      screen.queryByText(
        "8 seconds · low resolution · no audio · watermarked · low-risk shots only",
      ),
    ).not.toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: "View the generated three-image source set" }),
    ).toHaveAttribute("href", "#source-proof");
    expect(mocks.recordFunnelEventSafely).toHaveBeenCalledWith(
      expect.objectContaining({
        eventName: "landing_viewed",
        source: "server",
        userId: "user-1",
        path: "/",
        metadata: { sourcePage: "homepage" },
      }),
    );
  });
});
