import type { ShotTemplateDefinition } from "./types";

const frontConstraints = [
  "Do not invent unseen garment details.",
  "Keep garment color, shape, pattern, and visible construction consistent.",
];

export const mvpShotTemplates: ShotTemplateDefinition[] = [
  {
    templateId: "front_push_in",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "正面慢推近",
    description: "基于正面图做轻微推近，突出整体版型。",
    subjectKind: "any",
    requiredAssets: ["front"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["no_front_asset", "back_view", "detail_invention"],
    allowedMotion: ["slow_push_in", "subtle_parallax"],
    basePromptIntent: "Create a slow front-facing push-in product video.",
    systemConstraints: [...frontConstraints, "Do not show the back side."],
    postQaChecks: ["front_view_consistency", "color_consistency"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "front_pan",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "正面轻微平移",
    description: "基于正面图做轻微横向平移，适合商品主图展示。",
    subjectKind: "any",
    requiredAssets: ["front"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["no_front_asset", "shape_change", "pattern_change"],
    allowedMotion: ["subtle_pan", "minor_camera_slide"],
    basePromptIntent: "Create a subtle front-facing pan product video.",
    systemConstraints: frontConstraints,
    postQaChecks: ["front_view_consistency", "pattern_stability"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "product_float",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "商品悬浮展示",
    description: "白底或平铺图上的轻微悬浮展示，不真人化。",
    subjectKind: "any",
    requiredAssets: ["front", "flat_lay_or_white_background"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["human_generation", "turnaround", "non_clean_background"],
    allowedMotion: ["subtle_float", "soft_shadow_shift"],
    basePromptIntent: "Create a clean product float video from a flat-lay or white-background image.",
    systemConstraints: [...frontConstraints, "Do not create a human model."],
    postQaChecks: ["no_human_generation", "silhouette_consistency"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "model_front_pose",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "模特正面轻微姿态",
    description: "基于模特正面图做轻微姿态变化。",
    subjectKind: "any",
    requiredAssets: ["front", "model_front"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["turnaround", "large_body_motion", "back_view"],
    allowedMotion: ["small_pose_shift", "subtle_camera_motion"],
    basePromptIntent: "Create a subtle front-facing model pose video.",
    systemConstraints: [...frontConstraints, "Do not rotate the model away from the front view."],
    postQaChecks: ["human_anatomy", "front_view_consistency"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "front_crop_detail",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "正面局部裁切特写",
    description: "只裁切正面图中可见区域，做低风险局部展示。",
    subjectKind: "any",
    requiredAssets: ["front"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["invisible_detail_closeup", "detail_invention"],
    allowedMotion: ["crop_push_in", "subtle_focus_shift"],
    basePromptIntent: "Create a close crop from a visible area of the front image.",
    systemConstraints: [...frontConstraints, "Only crop visible areas from the source image."],
    postQaChecks: ["visible_area_only", "detail_consistency"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "fabric_macro",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "面料微距",
    description: "基于面料细节图做微距质感展示。",
    subjectKind: "any",
    requiredAssets: ["detail"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    detailTypes: ["fabric"],
    blockedConditions: ["no_detail_asset", "fabric_texture_invention"],
    allowedMotion: ["macro_push", "soft_focus_shift"],
    basePromptIntent: "Create a fabric macro video using an uploaded fabric detail image.",
    systemConstraints: ["Do not invent fabric texture.", "Only use visible fabric detail."],
    postQaChecks: ["texture_consistency", "no_invented_material"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "neckline_closeup",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "领口特写",
    description: "基于领口细节图做特写展示。",
    subjectKind: "any",
    requiredAssets: ["detail"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    detailTypes: ["neckline"],
    blockedConditions: ["no_neckline_detail", "neckline_change"],
    allowedMotion: ["closeup_push", "minor_camera_slide"],
    basePromptIntent: "Create a neckline closeup video using the uploaded neckline detail.",
    systemConstraints: ["Do not change the neckline shape.", "Do not add trims or buttons."],
    postQaChecks: ["neckline_consistency", "no_added_details"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "cuff_closeup",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "袖口特写",
    description: "基于袖口细节图做特写展示。",
    subjectKind: "any",
    requiredAssets: ["detail"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    detailTypes: ["cuff"],
    blockedConditions: ["no_cuff_detail", "added_button_or_embroidery"],
    allowedMotion: ["closeup_push", "subtle_focus_shift"],
    basePromptIntent: "Create a cuff closeup video using the uploaded cuff detail.",
    systemConstraints: ["Do not add buttons, embroidery, or seams.", "Keep cuff shape unchanged."],
    postQaChecks: ["cuff_consistency", "no_added_details"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "print_closeup",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "印花图案特写",
    description: "基于图案细节图做印花特写。",
    subjectKind: "any",
    requiredAssets: ["detail"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    detailTypes: ["print"],
    blockedConditions: ["no_print_detail", "pattern_drift"],
    allowedMotion: ["closeup_pan", "macro_push"],
    basePromptIntent: "Create a print closeup video using the uploaded print detail.",
    systemConstraints: ["Do not alter or hallucinate the printed pattern."],
    postQaChecks: ["print_stability", "pattern_consistency"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "back_display",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "背面展示",
    description: "基于背面图做背面静态展示。",
    subjectKind: "any",
    requiredAssets: ["back"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["no_back_asset", "front_to_back_hallucination"],
    allowedMotion: ["back_view_hold", "subtle_push_in"],
    basePromptIntent: "Create a back-facing product display from the uploaded back image.",
    systemConstraints: ["Only show the uploaded back view.", "Do not infer unseen back details."],
    postQaChecks: ["back_view_consistency", "no_unseen_back_details"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "front_to_back_cut",
    version: 1,
    status: "beta",
    riskLevel: "medium_high",
    displayName: "正背切换",
    description: "基于正面和背面图做剪切式正背切换，不做 360。",
    subjectKind: "any",
    requiredAssets: ["front", "back"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["no_back_asset", "full_360", "turnaround_animation"],
    allowedMotion: ["hard_cut_front_back", "brief_transition"],
    basePromptIntent: "Create a cut from the front view to the back view using uploaded front and back images.",
    systemConstraints: ["Do not create a full 360 turn.", "Do not generate unnatural head or body rotation."],
    postQaChecks: ["front_back_consistency", "transition_artifacts", "human_anatomy"],
    isTrialAllowed: false,
    requiresStrictReview: true,
  },
  {
    templateId: "scene_lifestyle_showcase",
    version: 1,
    status: "active",
    riskLevel: "medium",
    displayName: "场景氛围展示",
    description: "使用正面服装图和场景图生成氛围化展示。",
    subjectKind: "any",
    requiredAssets: ["front", "scene"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: [
      "garment_change",
      "scene_logo_or_text_copying",
      "people_from_scene_copying",
    ],
    allowedMotion: ["subtle_camera_motion", "soft_light_shift", "slow_push_in"],
    basePromptIntent:
      "Create a lifestyle product video using the garment from the front image and the uploaded scene image as background and atmosphere reference.",
    systemConstraints: [
      ...frontConstraints,
      "Use the scene image only as background, lighting, and mood reference.",
      "Do not copy people, faces, logos, storefront names, or readable text from the scene image.",
      "Do not show the back side.",
    ],
    postQaChecks: [
      "garment_consistency",
      "background_safety",
      "no_scene_people_or_text_copying",
    ],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "minimal_studio",
    version: 1,
    status: "active",
    riskLevel: "medium",
    displayName: "极简棚拍风",
    description: "基于正面图生成极简棚拍风展示，场景可轻微变化。",
    subjectKind: "any",
    requiredAssets: ["front"],
    consistencyRequirements: [],
    autoSelectAllowed: true,
    blockedConditions: ["garment_change", "brand_store_background"],
    allowedMotion: ["soft_light_shift", "subtle_camera_motion"],
    basePromptIntent: "Create a minimal studio product video while preserving the garment.",
    systemConstraints: [...frontConstraints, "The studio scene may change, but the garment must not change."],
    postQaChecks: ["garment_consistency", "background_safety"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "product_quarter_rotation",
    version: 1,
    status: "beta",
    riskLevel: "medium_high",
    displayName: "商品轻旋转 15-45°",
    description: "使用同一件服装的正面和侧面商品图生成有限角度旋转。",
    subjectKind: "product",
    requiredAssets: ["product_front", "product_side"],
    consistencyRequirements: ["same_garment"],
    autoSelectAllowed: false,
    blockedConditions: [
      "human_generation",
      "missing_matching_product_side",
      "rotation_over_45_degrees",
      "unseen_detail_invention",
    ],
    allowedMotion: ["product_rotation_15_45", "subtle_camera_hold"],
    basePromptIntent:
      "Rotate the garment-only product from its front view toward the uploaded side reference by 15 to 45 degrees.",
    systemConstraints: [
      "Do not create a person, hand, body, or model.",
      "Use only the uploaded product front and side views.",
      "Rotate no farther than the supported side reference, between 15 and 45 degrees.",
      "Do not invent unseen garment construction.",
    ],
    postQaChecks: [
      "no_human_generation",
      "garment_consistency",
      "bounded_rotation",
      "no_invented_details",
    ],
    isTrialAllowed: false,
    requiresStrictReview: true,
  },
  {
    templateId: "product_half_rotation",
    version: 1,
    status: "beta",
    riskLevel: "high",
    displayName: "商品连续 180° 转身",
    description: "使用同一件服装的正面、侧面和背面商品图生成半圈旋转。",
    subjectKind: "product",
    requiredAssets: ["product_front", "product_side", "product_back"],
    consistencyRequirements: ["same_garment"],
    autoSelectAllowed: false,
    blockedConditions: [
      "human_generation",
      "missing_matching_product_back",
      "full_360",
      "unseen_detail_invention",
    ],
    allowedMotion: ["product_rotation_180", "front_side_back_progression"],
    basePromptIntent:
      "Rotate the garment-only product continuously from the uploaded front view through the side view to the uploaded back view.",
    systemConstraints: [
      "Do not create a person, hand, body, or model.",
      "Use only the uploaded product front, side, and back views.",
      "Rotate only from front through side to back, no farther than 180 degrees.",
      "Do not continue into a 360-degree rotation.",
      "Do not invent unseen garment construction.",
    ],
    postQaChecks: [
      "no_human_generation",
      "garment_consistency",
      "front_side_back_order",
      "no_360_rotation",
      "no_invented_details",
    ],
    isTrialAllowed: false,
    requiresStrictReview: true,
  },
  {
    templateId: "model_quarter_turn",
    version: 1,
    status: "beta",
    riskLevel: "medium_high",
    displayName: "模特轻侧身 15-45°",
    description: "使用同一真人模特穿着同一件服装的正面和侧面图生成自然轻侧身。",
    subjectKind: "human_model",
    requiredAssets: ["model_front", "model_side"],
    consistencyRequirements: ["same_garment", "same_model"],
    autoSelectAllowed: false,
    blockedConditions: [
      "missing_matching_model_side",
      "model_identity_mismatch",
      "garment_mismatch",
      "unsupported_back_view",
      "unnatural_anatomy",
    ],
    allowedMotion: ["model_turn_15_45", "subtle_pose_transition"],
    basePromptIntent:
      "Create a natural 15 to 45 degree side turn using the uploaded front and side views of the same visible model wearing the same garment.",
    systemConstraints: [
      "Keep the same visible person throughout the shot.",
      "Keep human anatomy natural and preserve the original pose range.",
      "Keep garment color, silhouette, pattern, neckline, sleeves, and hem unchanged.",
      "Use only the uploaded model front and side views.",
      "Turn between 15 and 45 degrees and do not reveal an unsupported back view.",
    ],
    postQaChecks: [
      "same_visible_person",
      "human_anatomy",
      "garment_consistency",
      "bounded_model_turn",
      "no_unsupported_back_view",
    ],
    isTrialAllowed: false,
    requiresStrictReview: true,
  },
  {
    templateId: "model_half_turn",
    version: 1,
    status: "beta",
    riskLevel: "high",
    displayName: "模特连续转身 180°",
    description: "使用同一真人模特穿着同一件服装的正面、侧面和背面图生成连续半圈转身。",
    subjectKind: "human_model",
    requiredAssets: ["model_front", "model_side", "model_back"],
    consistencyRequirements: ["same_garment", "same_model"],
    autoSelectAllowed: false,
    blockedConditions: [
      "missing_matching_model_back",
      "model_identity_mismatch",
      "garment_mismatch",
      "full_360",
      "unnatural_anatomy",
    ],
    allowedMotion: ["model_turn_180", "front_side_back_progression"],
    basePromptIntent:
      "Create a natural continuous 180 degree turn from the uploaded front view through the side view to the uploaded back view of the same visible model and garment.",
    systemConstraints: [
      "Keep the same visible person throughout the shot.",
      "Keep human anatomy natural and preserve the original pose range.",
      "Keep garment color, silhouette, pattern, neckline, sleeves, and hem unchanged.",
      "Use only the uploaded model front, side, and back views.",
      "End at the uploaded back view and do not continue into a 360-degree turn.",
      "Do not swap the person's face, body shape, hair, or garment styling.",
      "Avoid unnatural head, arm, hand, hip, or leg rotation.",
    ],
    postQaChecks: [
      "same_visible_person",
      "human_anatomy",
      "garment_front_side_back_consistency",
      "front_side_back_order",
      "no_360_turn",
    ],
    isTrialAllowed: false,
    requiresStrictReview: true,
  },
];
