import type { ShotTemplateDefinition } from "./types";

const frontConstraints = [
  "Do not invent unseen garment details.",
  "Keep garment color, shape, pattern, and visible construction consistent.",
];

export const mvpShotTemplates: ShotTemplateDefinition[] = [
  {
    templateId: "front_push_in",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "正面慢推近",
    description: "基于正面图做轻微推近，突出整体版型。",
    requiredAssets: ["front"],
    blockedConditions: ["no_front_asset", "back_view", "detail_invention"],
    allowedMotion: ["slow_push_in", "subtle_parallax"],
    basePromptIntent: "Create a slow front-facing push-in product video.",
    systemConstraints: [...frontConstraints, "Do not show the back side."],
    postQaChecks: ["front_view_consistency", "color_consistency"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "front_pan",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "正面轻微平移",
    description: "基于正面图做轻微横向平移，适合商品主图展示。",
    requiredAssets: ["front"],
    blockedConditions: ["no_front_asset", "shape_change", "pattern_change"],
    allowedMotion: ["subtle_pan", "minor_camera_slide"],
    basePromptIntent: "Create a subtle front-facing pan product video.",
    systemConstraints: frontConstraints,
    postQaChecks: ["front_view_consistency", "pattern_stability"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "product_float",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "商品悬浮展示",
    description: "白底或平铺图上的轻微悬浮展示，不真人化。",
    requiredAssets: ["front", "flat_lay_or_white_background"],
    blockedConditions: ["human_generation", "turnaround", "non_clean_background"],
    allowedMotion: ["subtle_float", "soft_shadow_shift"],
    basePromptIntent: "Create a clean product float video from a flat-lay or white-background image.",
    systemConstraints: [...frontConstraints, "Do not create a human model."],
    postQaChecks: ["no_human_generation", "silhouette_consistency"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "model_front_pose",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "模特正面轻微姿态",
    description: "基于模特正面图做轻微姿态变化。",
    requiredAssets: ["front", "model_front"],
    blockedConditions: ["turnaround", "large_body_motion", "back_view"],
    allowedMotion: ["small_pose_shift", "subtle_camera_motion"],
    basePromptIntent: "Create a subtle front-facing model pose video.",
    systemConstraints: [...frontConstraints, "Do not rotate the model away from the front view."],
    postQaChecks: ["human_anatomy", "front_view_consistency"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "front_crop_detail",
    version: 1,
    status: "active",
    riskLevel: "low",
    displayName: "正面局部裁切特写",
    description: "只裁切正面图中可见区域，做低风险局部展示。",
    requiredAssets: ["front"],
    blockedConditions: ["invisible_detail_closeup", "detail_invention"],
    allowedMotion: ["crop_push_in", "subtle_focus_shift"],
    basePromptIntent: "Create a close crop from a visible area of the front image.",
    systemConstraints: [...frontConstraints, "Only crop visible areas from the source image."],
    postQaChecks: ["visible_area_only", "detail_consistency"],
    isTrialAllowed: true,
    requiresStrictReview: false,
  },
  {
    templateId: "fabric_macro",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "面料微距",
    description: "基于面料细节图做微距质感展示。",
    requiredAssets: ["detail"],
    detailTypes: ["fabric"],
    blockedConditions: ["no_detail_asset", "fabric_texture_invention"],
    allowedMotion: ["macro_push", "soft_focus_shift"],
    basePromptIntent: "Create a fabric macro video using an uploaded fabric detail image.",
    systemConstraints: ["Do not invent fabric texture.", "Only use visible fabric detail."],
    postQaChecks: ["texture_consistency", "no_invented_material"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "neckline_closeup",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "领口特写",
    description: "基于领口细节图做特写展示。",
    requiredAssets: ["detail"],
    detailTypes: ["neckline"],
    blockedConditions: ["no_neckline_detail", "neckline_change"],
    allowedMotion: ["closeup_push", "minor_camera_slide"],
    basePromptIntent: "Create a neckline closeup video using the uploaded neckline detail.",
    systemConstraints: ["Do not change the neckline shape.", "Do not add trims or buttons."],
    postQaChecks: ["neckline_consistency", "no_added_details"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "cuff_closeup",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "袖口特写",
    description: "基于袖口细节图做特写展示。",
    requiredAssets: ["detail"],
    detailTypes: ["cuff"],
    blockedConditions: ["no_cuff_detail", "added_button_or_embroidery"],
    allowedMotion: ["closeup_push", "subtle_focus_shift"],
    basePromptIntent: "Create a cuff closeup video using the uploaded cuff detail.",
    systemConstraints: ["Do not add buttons, embroidery, or seams.", "Keep cuff shape unchanged."],
    postQaChecks: ["cuff_consistency", "no_added_details"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "print_closeup",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "印花图案特写",
    description: "基于图案细节图做印花特写。",
    requiredAssets: ["detail"],
    detailTypes: ["print"],
    blockedConditions: ["no_print_detail", "pattern_drift"],
    allowedMotion: ["closeup_pan", "macro_push"],
    basePromptIntent: "Create a print closeup video using the uploaded print detail.",
    systemConstraints: ["Do not alter or hallucinate the printed pattern."],
    postQaChecks: ["print_stability", "pattern_consistency"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "back_display",
    version: 1,
    status: "beta",
    riskLevel: "medium",
    displayName: "背面展示",
    description: "基于背面图做背面静态展示。",
    requiredAssets: ["back"],
    blockedConditions: ["no_back_asset", "front_to_back_hallucination"],
    allowedMotion: ["back_view_hold", "subtle_push_in"],
    basePromptIntent: "Create a back-facing product display from the uploaded back image.",
    systemConstraints: ["Only show the uploaded back view.", "Do not infer unseen back details."],
    postQaChecks: ["back_view_consistency", "no_unseen_back_details"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
  {
    templateId: "front_to_back_cut",
    version: 1,
    status: "beta",
    riskLevel: "medium_high",
    displayName: "正背切换",
    description: "基于正面和背面图做剪切式正背切换，不做 360。",
    requiredAssets: ["front", "back"],
    blockedConditions: ["no_back_asset", "full_360", "turnaround_animation"],
    allowedMotion: ["hard_cut_front_back", "brief_transition"],
    basePromptIntent: "Create a cut from the front view to the back view using uploaded front and back images.",
    systemConstraints: ["Do not create a full 360 turn.", "Do not generate unnatural head or body rotation."],
    postQaChecks: ["front_back_consistency", "transition_artifacts", "human_anatomy"],
    isTrialAllowed: false,
    requiresStrictReview: true,
  },
  {
    templateId: "minimal_studio",
    version: 1,
    status: "active",
    riskLevel: "medium",
    displayName: "极简棚拍风",
    description: "基于正面图生成极简棚拍风展示，场景可轻微变化。",
    requiredAssets: ["front"],
    blockedConditions: ["garment_change", "brand_store_background"],
    allowedMotion: ["soft_light_shift", "subtle_camera_motion"],
    basePromptIntent: "Create a minimal studio product video while preserving the garment.",
    systemConstraints: [...frontConstraints, "The studio scene may change, but the garment must not change."],
    postQaChecks: ["garment_consistency", "background_safety"],
    isTrialAllowed: false,
    requiresStrictReview: false,
  },
];
